?# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
google_analytics: dbyll
title: 怡锅的鱼

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 怡锅的鱼

description: 生活不只眼前的苟且 还有诗和远方
# gavatar头像及Favicon
gavatar: http://img0.ph.126.net/0SVHduWIfIvgduIltWIhBQ==/1629740115257280873.jpg
favicon: http://img0.ph.126.net/0SVHduWIfIvgduIltWIhBQ==/1629740115257280873.jpg

author:
  name: 怡锅的鱼
  email: xiaoyisjz@126.com
  github: coolxiaoyi
  twitter: dbtek
  pinterest: asd123
  linkedin: asd123
  bio: 生活不只眼前的苟且 还有诗和远方
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate